ethereum/act

examples/transitions/invariant.md
examples/transitions/invariant.sol

Consider the following contract written in Solidity:
```
contract C {
uint x;
function f() public {      
if (x == 0)
x = 1;             
}
function g() public {
if (x == 1)
x = 2;
}
function h() public {
if (x == 2)
x = 0;
}
}
```
The added specification is an example of how to specify properties of this contract, with some things to discuss.
1. In this high level (no EVM) version of the specification language, I would suggest listing a contract's state variables in a `storage` section under a `contract`, where the types would match the ABI specification.
2. The state variables can then be used by the following function specifications without the need to specify a storage slot.
3. Contract invariants would be described in `invariants` also under `contract`. A property may hold over all …

Contract invariant example

---

tools/act.py
tools/solidity_to_act.py

This simple script takes the output of a Solidity compilation with `storageLayout` and `abi` requested and builds an Act specification skeleton for the given contracts.

Add Solidity standard-json to Act skeleton translator

---

.gitignore
src/Main.hs

- adds a `Module main where` delcaration to `main.hs`. Haskell language server needs this but `cabal` doesn' for some reason :woman_shrugging: 
- adds some more `nix` generated noise to the `.gitignore`

Support hls

---

.hlint.yaml
src/Prove.hs
src/Type.hs
tests/creation/create.act.typed.json
tests/multi/multi.act.typed.json
tests/safemath/safemathraw.act.typed.json
tests/smoke/smoke.act.typed.json
tests/token/transfer.act.typed.json

Travereses the AST for any `EthEnv` type expressiona and if found adds bounds for them as `if` style preconditions to all behaviours.
The full diff is a little cluttered due to some extraneous tidyups, the last commit contains the important logic.

Bound eth env

---

src/Main.hs

Since it breaks the output of the SMT backend if the user's terminal does not support emojis

Remove qed emoji

---

docs/act.md
src/Type.hs
tests/coq/exponent/exponent.act
tests/frontend/fail/missingdef0.act
tests/frontend/fail/missingdef1.act
tests/frontend/fail/missingdef2.act
tests/frontend/pass/storageread0.act
tests/frontend/pass/storageread1.act
tests/frontend/pass/storageread2.act
tests/hevm/fail/unspecced_storage/unspecced_storage.act

We now throw a type error if a storage read is not declared within the storage block.
e.g. The following will now fail with a type error (even if `y` is declared in the constructor).
```
storage
x => y
```
The following is correct:
```
storage
x => y
y
```
This fixes #75.

Type: fail if storage reads are undeclared

---

src/Lex.x
src/test/Test.hs
tests/frontend/pass/negative-literals.act

Fixes #61.
This does not include any typechecker logic, so obviously wrong statements like `uint a := -1` are admitted. A general check at the typechecker level would require us to implement evaluation for integer expressions, so I think it's fine to keep the implementation simple and leave this for the bounds checker.

Lex: allow negative integer literals

---

src/Enrich.hs
src/Extract.hs
src/HEVM.hs
src/K.hs
src/Main.hs
src/Prove.hs
src/RefinedAst.hs
src/Type.hs
src/act.cabal
tests/frontend/pass/creation/create.act.typed.json
tests/frontend/pass/multi/multi.act.typed.json
tests/frontend/pass/token/transfer.act.typed.json

Two major changes:
- Pull logic for adding constraints on the size of variables referenced by the invariant expressions into Enrich.hs
- Add a new module (Extract) that contains all logic used to extract information from the AST
This also fixes a bug where type bounds for calldata / env vars referenced in the invariant were missing.

Refactor: Enrich Invariants

---

default.nix
src/HEVM.hs
src/act.cabal

This PR adds a `ci` flag to the build system that:
- forces all warnings to be errors
- enables the optimizer (`-O2`)
The `ci` flag is enabled for all `nix` builds.
Local builds (`cabal v2-build`) will still succeed in the prescense of warnings (although the same set of warnings will be shown in both configs).
We currently ignore the following compiler warnings in both configurations:
- orphan instances
- ~deprecated~
This is built on top of #89, I'll retarget to master once it's merged.

Enfore build cleanliness

---

src/RefinedAst.hs
src/SMT.hs
tests/invariants/fail/concretebase.act
tests/invariants/fail/concreteexponent.act
tests/invariants/fail/symbolicexponent.act
tests/invariants/pass/concretebase.act
tests/invariants/pass/concreteexponent.act

Closes #99, i.e. we can now pass any exponentiation where the exponent is concrete to the SMT backend even though it has no support for exponentiation. This does not however include any algebraic analysis to attempt to simplify away symbolic values.
I'm a bit uncertain on how division is to be dealt with. Currently I'm using `div` and `mod` from Haskell's Prelude (rather than `quot` and `rem`). This is because they truncate towards negative infinity, which is what the EVM seems to be doing according to the yellow paper. But what exactly are we trying to agree with? The EVM? In that case `x/0` should be `0`, so we need a special case for that. Or Solidity? Or our other backends?

Simplify exponentiation in SMT backend

---

src/Extract.hs
src/Main.hs
src/Print.hs
src/RefinedAst.hs
src/SMT.hs
src/act.cabal
src/test/Test.hs

This closes #63.
Notable changes:
- Pretty printed counterexamples
- Reworked solver interaction code so that we now share a single long running solver instance between all queries. This is a little more involved, but makes extracting the models much easier
- The `Inv` constructor for the `Query` type has been reworked a little to bundle all the individual smt queries related to each invariant in one type
- The various `locsFrom*` / `ethEnvFrom*` functions in `Extract.hs` now deduplicate their output, making them more ergononomic at the cost of some redundent calls to `nub`
Pretty printing / colorful output is achieved using the [`ansi-wl-pprint`](https://hackage.haskell.org/package/ansi-wl-pprint-0.6.7.3/docs/Text-PrettyPrint-ANSI-Leijen.html#v:encloseSep) library. It may be worth …

SMT: Model Extraction & Pretty Counterexamples

---

src/Extract.hs
src/Type.hs
src/test/Test.hs
tests/invariants/fail/ethEnv.act
tests/invariants/pass/ethEnv.act

bytestrings are not well supported in act at the moment so this lets us verify contracts involving `bytes32` in hevm and Coq, and it should anyway be a nice optimisation.

represent bytes32 as an int internally

---

nix/sources.json
src/HEVM.hs
src/Main.hs

Bumps us to latest dapptools, which lets us fix the issue where act was showing QED if the solver timed out in the hevm backend.

bump dapptools

---

src/CLI.hs
src/Coq.hs
src/Enrich.hs
src/HEVM.hs
src/K.hs
src/Print.hs
src/SMT.hs
src/Syntax.hs
src/Syntax/TimeAgnostic.hs
src/Syntax/Types.hs
src/Syntax/Untyped.hs
src/Type.hs
src/act.cabal
src/test/Test.hs

This changes absolutely no behavior, but makes it possible for the various backends to generate error messages which include a pointer to the source file position corresponding to the error. It will be used when unifying error handling.

Add source file positions to typed expressions

---

doc/src/language.md
src/Type.hs

Removes filtering out variables from the environment that do not appear at the LHS of storage update declarations.
The main reason for this is that the strategy for removing variables with contract types was wrong, so it is a prerequisite for an upcoming PR that add support for contract types. 
Note that now we lift the restriction that storage variables that are used in storage update declaration have to be explicitly mentioned in the storage updated declarations.

No filtering out variables from environment

---

src/SMT.hs
tests/invariants/pass/case.act

This adds case conditions to the invariant constraints so that they are taken into account when checking invariants. This was a bug introduced by #145, that split preconditions into preconditions (i.e., ensures) and case conditions. 
It also adds a test that checks whether the case conditions are taken into account when proving invariants.

Fix bug related to missing constraints from case conditions.

---

src/act.cabal

For open games I've needed to expose the time-agnostic AST. Can we add it to the list of exported modules?

TimeAgnostic to exposed modules

---

doc/book.toml
flake.nix

Adds latex support to the documentation using: https://github.com/lzanini/mdbook-katex

doc: add latex support

---

src/CLI.hs
src/HEVM.hs
tests/hevm/pass/safemath/safemath.act
tests/hevm/pass/safemath/safemath.sol
tests/hevm/pass/transfer-simple/transfer.act

This PR includes:
- New check that checks whether all reachable successes in Solidity are described by the Act spec. This is checked by asserting that the function selector is not equal to the selectors of the interfaces in Act, and trying to find reachable successes.
- Removal of the range assertions in the initial calldata.
- Some cleanup and moving functions from CLI to HEVM.
- Some pretty colors for the output of Act.

ABI exhaustiveness check

---

src/hie.yaml

Im not sure what the HLS uses `hie.yaml` for, but I was getting this gignatic error from it that wouldnt let me use the LSP:
So I just renamed `act-internal` to `act` in `hie.yaml` and now its working smooth. Dk if this might break any of your envs tho.

hie.yaml small rename

---

src/Syntax/TimeAgnostic.hs
src/Syntax/Untyped.hs
tests/frontend/pass/case/case.act.typed.json
tests/frontend/pass/creation/create.act.typed.json
tests/frontend/pass/multi/multi.act.typed.json
tests/frontend/pass/safemath/safemathraw.act.typed.json
tests/frontend/pass/smoke/smoke.act.typed.json
tests/frontend/pass/token/transfer.act.typed.json

A couple of edits to the JSON printer of `Exp` so that it produces more consistent output.

Nits in the JSON printer

---

src/Act/CLI.hs
src/Act/HEVM.hs

Removes `veriOpts` parameter that is now redundant after moving to hevm's generic monad.

Remove redundant parameter

---

src/Act/CLI.hs
src/Act/HEVM.hs
src/Act/HEVM_utils.hs

This PR includes:
- Properly threading the Act state between constructor and subsequent behaviours so that the counter for symbolic address names so that there are no name collisions if behaviours create new constructs. (Note: contract creation in behaviours has not been tested yet due to hevm returning only failed states.)
- Some general cleanup (removing comments, fixing typos)

Proper threading of the Act state and some cleanup

---

src/Act/SMT.hs
tests/postconditions/pass/amm.act

This PR adds assertions that storage variables that are not explicitly modified remain constant. This was missing from the SMT encoding of postconditions.
Also, adds the AMΜ contract as a test in the postconditions directory that relies on these assertion to be proved.

Add constant assertions to SMT encoding of postconditions
